---
# Create  server policies specific to Converged Infrastrucure stack
- name: "Create C240 Standalone Intersight Managed Server Policies"
  vars:
    api_info: &api_info_org_moid
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info_org_moid
    resource_path: /organization/Organizations
    query_params:
      $filter: "Name eq '{{ org_name }}'"
  register: intersight_org
  delegate_to: localhost
  tags: always
  run_once: true

# Collect information on existence of Boot Order Policy, LAN Connectivity Policy, and
# IMC Management IP Pool
#- include_tasks: gather_policy_info.yml





# Create Cohesity Boot Order Policy
- include_tasks: create_boot_order_policies.yml

# Create BIOS Policy
- include_tasks: create_bios_policies.yml




# Create IPMI over LAN Policy to enable IPMI over LAN
- include_tasks: create_ipmi_policy.yml

# Create SerialOver LAN Policy
- include_tasks: create_sol_policy.yml


# Create Storage Policy
- include_tasks: create_storage_policy.yml

# Create Adapter Policy (VIC1457 or VIC 1467)
- include_tasks: create_adapter_policy.yml
